// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwncdkekeqdsftktqcuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3bmNka2VrZXFkc2Z0a3RxY3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MzE3ODAsImV4cCI6MjA1NjQwNzc4MH0.1gizQJre-1PxEbVIICMIqSP-I5q9e8gudywiH9j3t_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);